[workspace]
authors = ["Cam Bracken <cameron.bracken@pnnl.gov>"]
channels = ["conda-forge"]
name = "tethys_integration_metarepo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = "*"
python = ">=3.12,<3.13"
packaging = ">=24.1,<25.0"

[pypi-options]
extra-index-urls = ["https://msd-live.github.io/msdlive-cli-distro/simple/"]

[pypi-dependencies]
msdlive-cli = "*"
awscli = { url = "https://github.com/MSD-LIVE/awscli/raw/main/dist/awscli-2.17.55-py3-none-any.whl" }
