# base config

years: [1975, 1990, 2005, 2010, 2015, 2020]
resolution: 0.125
bounds: [25.0625, 52.9375, -124.9375, -67.0625]  # [lat_min, lat_max, lon_min, lon_max] # CONUS

demand_type: consumption


output_dir: ./output/

gcam_db:  ../gcam-usa-im3/20240606_to_be_validated/database_rcp45cooler_ssp3  # only care about historical though


# list of map files
map_files:
  - ./data/maps/states.tif
  - ./data/maps/statebasins.tif
  - ./data/maps/USA.tif
  - ./data/maps/USAbasins.tif


proxy_files:

  ./data/population/ssp3_{year}.tif:
    variables: Population
    years: [2010, 2020]

  ./data/demeter/output_wo_harvforest_demeter_CONUS_harmonized_im3_demeter_rcp45cooler_ssp3_{year}.nc:
    variables: [c3_crop_irr, Corn_irr, Wheat_irr, Wheat_winter_irr, Soy_irr, Barley_irr, Barley_winter_irr, Rye_irr, Rye_winter_irr, Cassava_irr, Citrus_irr, Cocoa_irr, Coffee_irr, Cotton_irr, DatePalm_irr, FodderGrass_irr, Grapes_irr, GroundNuts_irr, Millet_irr, OilPalm_irr, Potatoes_irr, Pulses_irr, RapeSeed_irr, Rice_irr, Sorghum_irr, Sugarbeet_irr, Sugarcane_irr, sunflower_irr, miscanthus_irr, switchgrass_irr, sunflower_irr, CornTropical_irr, SoyTropical_irr]
    years: [2010, 2015, 2020]
    flags: [cell_area_share, long_name_as_name]

  ./data/livestock/5_{variable}_{year}_Da.tif:
    variables: {Buffalo: Bf, Cattle: Ct, Sheep: Sh, Goat: Gt, Chicken: Ch, Duck: Dk, Pig: Pg}
    years: 2010

  ./data/powerplants/historical_gppd_im3_tethys_plants.nc:
    variables: ['Biomass', 'Coal', 'Cogeneration', 'Gas', 'Geothermal', 'Hydro', 'Nuclear', 'Oil', 'Other', 'Petcoke', 'Solar', 'Storage', 'Waste', 'Wave and Tidal', 'Wind']
    years: 2015


downscaling_rules:

  Domestic:                      Population

  Electricity:
    # some states currently have no biomass plants, so use location of existing coal (like a retrofit)
    electricity/biomass:         [Biomass, Coal]
    electricity/coal:            Coal
    electricity/gas:             Gas
    electricity/geothermal:      Geothermal
    electricity/nuclear:         Nuclear
    electricity/refined liquids: Oil
    electricity/solar:           Solar
    # excluding electrcity/hydro, which is not cooling water

  Irrigation:
    Corn:        [Corn_irr, CornTropical_irr]
    Wheat:       [Wheat_irr, Wheat_winter_irr]
    Rice:         Rice_irr
    RootTuber:   [Cassava_irr, Potatoes_irr]
    OilCrop:     [Soy_irr, GroundNuts_irr, RapeSeed_irr, sunflower_irr, SoyTropical_irr]
    SugarCrop:   [Sugarbeet_irr, Sugarcane_irr]
    OtherGrain:  [Barley_irr, Barley_winter_irr, Rye_irr, Rye_winter_irr, Millet_irr, Sorghum_irr]
    FiberCrop:    Cotton_irr
    FodderGrass: [FodderGrass_irr]
    FodderHerb:   c3_crop_irr
    biomass:     [miscanthus_irr, switchgrass_irr]
    MiscCrop:    [Citrus_irr, Cocoa_irr, Coffee_irr, DatePalm_irr, Grapes_irr, Pulses_irr]
    PalmFruit:    OilPalm_irr

  Livestock:
    Beef:        [Buffalo, Cattle]
    Dairy:       [Buffalo, Cattle]
    Pork:         Pig
    Poultry:     [Chicken, Duck]
    SheepGoat:   [Sheep, Goat]

  Manufacturing:  Population
  Mining:         Population

# affects irrigation and livestock sectors, more iterations means state-level totals (e.g., sum all crops within state) will better match with GCAM
supersector_iterations: 0  # turning off because state totals do not match USA total value


temporal_config:

  Domestic:
    method: domestic
    kwargs:
      tasfile: ./data/monthly/Tavg_HDD_CDD/Tavg_HDD_CDD_Historical_*.nc
      tasvar: Tavg
      rfile: ./data/monthly/DomesticR.nc
      
  Electricity:
    method: electricity
    kwargs:
      hddfile: ./data/monthly/Tavg_HDD_CDD/Tavg_HDD_CDD_Historical_*.nc
      cddfile: ./data/monthly/Tavg_HDD_CDD/Tavg_HDD_CDD_Historical_*.nc
      hddvar: HDD
      cddvar: CDD
      gcam_db: ../gcam-usa-im3/20240606_to_be_validated/database_rcp45cooler_ssp3
      regionfile: ./data/maps/states.tif
      
  Irrigation:
    method: weights
    kwargs:
      weightfile: ./data/monthly/deficit/irrigation_weight_rcp45cooler.nc  # need to caclulate historical GSI
      prenormalized: true
